### ISSUE TITLE
Import Original Watchlist Button on Main Page is not working & Profile page spam

### ISSUE THREAD

**Issue by Lyvric** [Derro8/Crunchyroll-Profiles#4]
On Press nothing happens. Also seems like some other Buttons have the same problem.

Used Browser: Firefox 117.0.1

Error:
```text
TypeError: js.data is undefined [sandbox eval code:174:9]
    importCurrentWatchlist sandbox eval code:174
    (Async: EventListener.handleEvent)
    importCurrentWatchlist sandbox eval code:167
```

**Comment by Derro8** [comment]
I really should've tested that beforehand lol, also thanks for the DE translations.

Please try the newest update and let me know if this still happens.

**Comment by Lyvric** [comment]
Still not working, but the Error changed a little.

```text
TypeError: js.data is undefined 7 sandbox eval code:175:9
    importCurrentWatchlist sandbox eval code:175
    (Async: EventListener.handleEvent)
    importCurrentWatchlist sandbox eval code:168
    (Async: EventListener.handleEvent)
    createButton sandbox eval code:49
    <anonym> sandbox eval code:164
    inject resource://gre/modules/ExtensionContent.sys.mjs:587
    AsyncFunctionNext self-hosted:852
```

Looked in the code myself. I don't really understand it but could it be that the URL's are not working somehow?
src/modules/patch.js/409 & /452

---

Also found a second bug, where the Profile Page is opening for infinity if no Account was created.
It is almost impossible to create one Account.

**Comment by Derro8** [comment]
> it but could it be that the URL's are not working somehow?

This seems to be it for some reason adding &check=false to the URL will result in the response to look like this

```json
{"code":"content.error.invalid_auth_token","context":[]}
```

changing it to literally anything but false seems to make it work try out the newest update and let me know if this still happens since I'm unable to replicate the error.

---

> Also found a second bug, where the Profile Page is opening for infinity if no Account was created.
It is almost impossible to create one Account.

I've added a 30 second cool down on the page opening hopefully that should help.

**Comment by Derro8** [comment]
Ah, I did some poking around the CR APK and found that the URL needs the account's uuid as well `/content/v2/{account_uuid}/watch-history` this should be fixed now.
